name: $(Date:yyyyMMdd).$(Rev:.r)
trigger:
  branches:
    include:
    - releases/*
    - develop
jobs:
- job:
  displayName: Spinning up test infrastructure
  timeoutInMinutes: 1440
  steps:
  - powershell: cd ci; ./booknode.ps1
  - powershell: cd infrastructure/images; ./preparevmimages.ps1 win2016-soe,win2016-sql2016dbrs,win2016-ad
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-soe *" } ) ) { exit 1 }
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-sql2016dbrs *" } ) ) { exit 1 }
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-ad *" } ) ) { exit 1 }
  - powershell: cd infrastructure/stacks/dev-ad-sql2016dbrs-crmempty-test; vagrant destroy CRM01, DB01 --force; vagrant up --provider virtualbox;
  - powershell: cd ci;./releasenode.ps1
