name: $(Date:yyyyMMdd).$(Rev:.r)
trigger:
  branches:
    include:
    - release-*
    exclude:
    - develop
jobs:
- job:
  displayName: Relesing the module
  steps:
  - powershell: ./publishing/psmodulepublishing.ps1
    displayName: Releasing the module
    errorActionPreference: continue
